### ISSUE TITLE
Unable to see locations by default within a distance limit.

### ISSUE THREAD

**Issue by pranireddy9** [bjorn2404/jQuery-Store-Locator-Plugin#144] opened 2016-08-06 16:20 UTC
HI,

when i open the locations page it will give distance alert if the no store is within the 50miles. So it is showing all the stores on map. That is fine. But my question is if something is within 50miles, i am able to see only users current location not nearest locations on map, Eventhough I have locations within 50miles. I want to see the locations within 50miles on map, along with the current users location. does any one have any idea? 

If I zoom in then i can see the locations. I need to see by default.

![image](https://cloud.githubusercontent.com/assets/19625325/17457771/bf64fb80-5bc6-11e6-945c-70e35514e830.png)

**Comment by bjorn2404** [comment] 2016-08-06 23:50
This is a duplicate of a previous issue you submitted. Don't submit duplicate issues for the same thing.

**Closed by bjorn2404** 2016-08-06 23:50 UTC
